/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package fireship.student.management.system;

import com.mysql.cj.jdbc.ClientPreparedStatement;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.ResultSet;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author E-ZONE
 */
public class ManageData extends javax.swing.JInternalFrame {

    
    Connection conn = null;
    ClientPreparedStatement ptss;
    ClientPreparedStatement ptss2;
    ResultSet rs = null;
    ResultSet rs2 = null;
    int selectedID;
    /**
     * Creates new form ManageData
     */
    public ManageData() {
        initComponents();
        table();
    
    }
    
    
    
    public void table(){
    
       try {
           
           try {
               conn = DBConnection.connect();
           } catch (SQLException ex) {
               Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
           }
           
           
           String data = "SELECT StudentID AS 'Student ID',FullName AS 'Full Name',Address,NIC,MobileNo,Email FROM students";
           ptss = (ClientPreparedStatement) conn.prepareStatement(data);
           rs = ptss.executeQuery();
           
           table.setModel(DbUtils.resultSetToTableModel(rs));
           
           
           
       } catch (SQLException ex) {
                 Logger.getLogger(ManageData.class.getName()).log(Level.SEVERE, null, ex);
             }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        insert_name_update = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        insert_address_update = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        insert_nic_update = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        insert_email_update = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        insert_mobile_update = new javax.swing.JTextField();
        inset_update = new javax.swing.JButton();
        picture_update = new javax.swing.JLabel();
        delete = new javax.swing.JButton();
        search = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SystemIcons/UPDATE.png"))); // NOI18N
        jLabel1.setText("MANAGE DATA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.setRowMargin(2);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table);

        insert_name_update.setBackground(new java.awt.Color(255, 204, 0));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel2.setText("Name");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel3.setText("Address");

        insert_address_update.setBackground(new java.awt.Color(255, 204, 0));
        insert_address_update.setColumns(20);
        insert_address_update.setRows(5);
        jScrollPane1.setViewportView(insert_address_update);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel4.setText("NIC");

        insert_nic_update.setBackground(new java.awt.Color(255, 204, 0));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel5.setText("Email");

        insert_email_update.setBackground(new java.awt.Color(255, 204, 0));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel6.setText("Mobile No");

        insert_mobile_update.setBackground(new java.awt.Color(255, 204, 0));

        inset_update.setBackground(new java.awt.Color(0, 255, 153));
        inset_update.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        inset_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SystemIcons/1491265004_plus.png"))); // NOI18N
        inset_update.setText("UPDATE DATA");
        inset_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inset_updateActionPerformed(evt);
            }
        });

        picture_update.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        picture_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SystemIcons/books out.png"))); // NOI18N
        picture_update.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 4, true));
        picture_update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                picture_updateMouseClicked(evt);
            }
        });

        delete.setBackground(new java.awt.Color(255, 102, 102));
        delete.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SystemIcons/DELETE.png"))); // NOI18N
        delete.setText("DELETE RECORD");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        search.setBackground(new java.awt.Color(0, 255, 204));
        search.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
                    .addComponent(search))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(insert_name_update)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE))
                                .addGap(43, 43, 43)
                                .addComponent(picture_update, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(86, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(delete)
                                .addGap(18, 18, 18)
                                .addComponent(inset_update, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(256, 256, 256))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(11, 11, 11)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(insert_nic_update)
                            .addComponent(insert_email_update)
                            .addComponent(insert_mobile_update, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(insert_name_update, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 36, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(picture_update, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(insert_nic_update, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(insert_email_update, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(insert_mobile_update, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inset_update, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inset_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inset_updateActionPerformed

        try {
            String getname = insert_name_update.getText().trim();
            String getaddress = insert_address_update.getText();
            String getnic = insert_nic_update.getText();
            String getemail = insert_email_update.getText();
            String getmobile = insert_mobile_update.getText();
            
            String update = "UPDATE students SET FullName='"+getname+"',Address='"+getaddress+"',NIC='"+getnic+"',Email='"+getemail+"',MobileNo='"+getmobile+"' WHERE StudentID="+selectedID;
            ptss = (ClientPreparedStatement) conn.prepareStatement(update);
            ptss.execute();
            
            table();
            JOptionPane.showMessageDialog(null, "Updated!");
            
            
            
            
//        try {
//
//            String name = insert_name.getText().trim();
//            String address = insert_address.getText();
//            String nic = insert_nic.getText();
//            String email = insert_email.getText();
//            String mobile = insert_mobile.getText();
//
//            File b = new File(pathGlobal);
//            FileInputStream img = null;
//            try {
//                img = new FileInputStream(b);
//            } catch (FileNotFoundException ex) {
//                Logger.getLogger(Insert_internal.class.getName()).log(Level.SEVERE, null, ex);
//            }
//
//            Connection conn = null;
//
//            try {
//                conn = DBConnection.connect();
//            } catch (SQLException ex) {
//                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
//            }
//
//            String inserQuery = "INSERT INTO students (FullName,Address,NIC,MobileNo,Email,Picture) VALUES (?,?,?,?,?,?)";
//
//            ClientPreparedStatement insert = (ClientPreparedStatement) conn.prepareStatement(inserQuery);
//
//            insert.setString(1, name);
//            insert.setString(2, address);
//            insert.setString(3, nic);
//            insert.setString(4, mobile);
//            insert.setString(5, email);
//            insert.setBlob(6, img);
//
//            insert.executeUpdate();
//            JOptionPane.showMessageDialog(null, "New Student Added!");
//
//        } catch (SQLException ex) {
//            Logger.getLogger(Insert_internal.class.getName()).log(Level.SEVERE, null, ex);
//        }
        } catch (SQLException ex) {
            Logger.getLogger(ManageData.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_inset_updateActionPerformed

    private void picture_updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_picture_updateMouseClicked

//        JFileChooser file = new JFileChooser();
//        file.setCurrentDirectory(new File(System.getProperty("user.home")));
//        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.images","*.jpg","*.png");
//        file.addChoosableFileFilter(filter);
//        int result = file.showSaveDialog(null);
//
//        if(result == JFileChooser.APPROVE_OPTION){
//            File selectfile = file.getSelectedFile();
//            String path = selectfile.getAbsolutePath();
//
//            ImageIcon icon = new ImageIcon(path);
//            Image image =icon.getImage();
//            Image modify = image.getScaledInstance(186, 170, java.awt.Image.SCALE_SMOOTH);
//            icon = new ImageIcon(modify);
//
//            picture.setIcon(icon);
//            pathGlobal = path;

        //}
    }//GEN-LAST:event_picture_updateMouseClicked

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
       
        String message = "Do you want to Delete this record?";
        int reply = JOptionPane.showConfirmDialog(null, message, "Delete",JOptionPane.YES_NO_OPTION);
        
        if(reply == JOptionPane.YES_OPTION){
        
            try {
                String delQuery = "DELETE FROM students WHERE StudentID=?";
                ptss = (ClientPreparedStatement) conn.prepareStatement(delQuery);
                ptss.setInt(1, selectedID);  
                ptss.execute();
                
                 
                table();
                
               
            } catch (SQLException ex) {
                Logger.getLogger(ManageData.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
            
        
        }
        
        
        
    }//GEN-LAST:event_deleteActionPerformed

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
       
         try {                                   
             
             String userInput = search.getText().trim();
             System.out.println(userInput);
             
             try {
                 conn = DBConnection.connect();
             } catch (SQLException ex) {
                 Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
             }
             
            
             String data = "SELECT StudentID AS 'Student ID',FullName AS 'Full Name',Address,NIC,MobileNo,Email FROM students WHERE NIC LIKE '%"+userInput+"%'";
             ptss2 = (ClientPreparedStatement) conn.prepareStatement(data);
            // ptss2.setString(1, userInput);
             rs2 = ptss2.executeQuery();
             
             table.setModel(DbUtils.resultSetToTableModel(rs2));
             
             
         } catch (SQLException ex) {
                 Logger.getLogger(ManageData.class.getName()).log(Level.SEVERE, null, ex);
             }
        
        
    }//GEN-LAST:event_searchKeyReleased

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        
        
        try {
            int rowIndex = table.getSelectedRow();
            selectedID = (int) table.getModel().getValueAt(rowIndex, 0);
            
            System.out.println(selectedID);
            
            
            String getRowData = "SELECT * FROM students WHERE StudentID="+selectedID;
            ptss = (ClientPreparedStatement) conn.prepareStatement(getRowData);
            rs = ptss.executeQuery();
            
            if(rs.next()){
                
                insert_name_update.setText(rs.getString("FullName"));
                insert_address_update.setText(rs.getString("Address"));
                insert_nic_update.setText(rs.getString("NIC"));
                insert_email_update.setText(rs.getString("Email"));
                insert_mobile_update.setText(rs.getString("MobileNo"));
                
                InputStream img = rs.getBinaryStream("Picture");
                picture_update.setIcon((Icon) img);
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(ManageData.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_tableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delete;
    private javax.swing.JTextArea insert_address_update;
    private javax.swing.JTextField insert_email_update;
    private javax.swing.JTextField insert_mobile_update;
    private javax.swing.JTextField insert_name_update;
    private javax.swing.JTextField insert_nic_update;
    private javax.swing.JButton inset_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel picture_update;
    private javax.swing.JTextField search;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
